[package]
name = "futures-timer"
version = "0.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/futures-timer"
homepage = "https://github.com/alexcrichton/futures-timer"
documentation = "https://docs.rs/futures-timer"
description = """
Timeouts and intervals for futures.
"""

[dependencies]
futures = { git= "https://github.com/tamasblummer/futures-rs.git", tag = "0.2.1" }
